[workspace]
members = [
    "ic-agent/",
    "ic-identity-hsm/",
    "ic-types/",
    "ic-utils/",
    "icx/",
    "icx-proxy/",
    "ref-tests/",
]

[patch.crates-io]
ic-types = { path = "./ic-types", version = "0.1", features = [ "serde" ] }

[patch.crates-io.candid]
git = "https://github.com/dfinity/candid.git"
branch = "binread"
